### ISSUE TITLE
TFOD

### ISSUE THREAD

**Issue by Eric2422** [chsRobotix/2024-2025IntoTheDeep#3]
TFOD is an image recognition software that would aid in picking up samples.

**Comment by FunnyLookingCat** [comment]
I thinking of making a new branch, I'm currently looking through old repos of FTC for samples

**Comment by FunnyLookingCat** [comment]
Nvm FTC SDK no longer supports TFOD or tensorflow
[](https://ftc-community.firstinspires.org/t/is-the-machine-learning-toolchain-is-closed-for-the-2024-offseason/1100)

**Comment by FunnyLookingCat** [comment]
https://ftc-community.firstinspires.org/t/is-the-machine-learning-toolchain-is-closed-for-the-2024-offseason/1100

link here for explanation^

i will be looking into easy-opencv
